<?php 


?>

<header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
            <span class="mdl-layout__title">Bangalore Lake Dashboard</span>
            <div class="mdl-layout-spacer"></div>

            <div class="avatar-dropdown">
                <button id="site-toolbar-account" class="mdl-button mdl-js-button mdl-button--icon">
                    <i class="material-icons">account_circle</i>
                </button>
               
                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="site-toolbar-account">
                    
                    <li class="mdl-menu__item">Some Action</li>
                    <li class="mdl-menu__item">Another Action</li>
                    <li disabled class="mdl-menu__item">Disabled Action</li>
                    <li class="mdl-menu__item">Yet Another Action Action Action</li>
                </ul>
            </div>

        </div>
    </header>

