<div class="mdl-cell docs-text-styling mdl-shadow--4dp mdl-cell--3-col">

        <ul class="lake-edit-links mdl-list ">
            
                <li class="mdl-list__item">
                    <a href="#" class="mdl-components__link mdl-component"> 
                        <span class="mdl-list__item-primary-content">General information</span> 
                    </a>
                </li>
                
                <li class="mdl-list__item">
                    <a href="#" class="mdl-components__link mdl-component"> 
                        <span class="mdl-list__item-primary-content">Zones/Boundaries</span> 
                    </a>
                </li>

                 <li class="mdl-list__item">
                    <a href="#" class="mdl-components__link mdl-component"> 
                        <span class="mdl-list__item-primary-content">Inlet/Outlets</span> 
                    </a>
                </li>

                <li class="mdl-list__item">
                    <a href="#" class="mdl-components__link mdl-component"> 
                        <span class="mdl-list__item-primary-content">Bathymetry</span> 
                    </a>
                </li>

                <li class="mdl-list__item">
                    <a href="#" ng-click="goto_stage_volume_page(lakeId)" class="mdl-components__link mdl-component"> 
                        <span class="mdl-list__item-primary-content">Stage volume</span> 
                    </a>
                </li>

                 <li class="mdl-list__item">
                    <a href="#" class="mdl-components__link mdl-component"> 
                        <span class="mdl-list__item-primary-content">Stage area</span> 
                    </a>
                </li>

                <li class="mdl-list__item">
                    <a href="#" class="mdl-components__link mdl-component"> 
                        <span class="mdl-list__item-primary-content">Evaporation data</span> 
                    </a>
                </li>


        </ul>
    </div> <!-- edit:sidebar -->


