 <div id="footer">
  <footer class="mdl-mega-footer">
        
            <div class="mdl-mega-footer__top-section">
                <div class="mdl-mega-footer__left-section">
                    <button class="mdl-mega-footer__social-btn"></button>
                    <button class="mdl-mega-footer__social-btn"></button>
                    <button class="mdl-mega-footer__social-btn"></button>
                </div>
                <div class="mdl-mega-footer__right-section">
                    <a href="">Link 1</a>
                    <a href="">Link 2</a>
                    <a href="">Link 3</a>
                </div>
            </div>
       
    </footer>
 </div>
