<div class="mdl-layout__drawer">
    <span class="mdl-layout-title" style="background-color: #6ab344;">
        <a href="#"  style="text-decoration: none;color:white">Admin DashBoard</a>
    </span>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="#">General Information</a>
        <a class="mdl-navigation__link" href="/admin/view/lake/io/standard-template.php">Stage Area</a>
        <a class="mdl-navigation__link" href="/admin/view/lake/io/list.php">Inlets/Outles</a>
        <a class="mdl-navigation__link" href="/admin/view/lake/io/standard-template.php">Stage Volume</a>
        <a class="mdl-navigation__link" href="/admin/view/lake/io/standard-template.php">Bathymetry</a>
        <a class="mdl-navigation__link" href="/admin/view/lake/io/standard-template.php">Lake Boundry</a>
        <a class="mdl-navigation__link" href="/admin/view/lake/io/standard-template.php">Lake Zones</a>
        <a class="mdl-navigation__link" href="#">Water Balance</a>
        <a class="mdl-navigation__link" href="#">Water Quality</a>
        <a class="mdl-navigation__link" href="#">Evaporation Data</a>
    </nav>
</div>