<div class="mdl-layout__drawer">
    <span class="mdl-layout-title" style="background-color: #6ab344;color: #6ab344;">
        Title
    </span>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
    </nav>
</div>