<div class="mdl-layout__drawer">
    <span class="mdl-layout-title" style="background-color: #6ab344;color: #6ab344;">
        Title
    </span>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="#">General Information</a>
        <a class="mdl-navigation__link" href="#">Stage Area</a>
        <a class="mdl-navigation__link" href="/admin/view/lake/io/create.php">Inlets/Outles</a>
        <a class="mdl-navigation__link" href="#">Stage Volume</a>
        <a class="mdl-navigation__link" href="#">Bathymetry</a>
        <a class="mdl-navigation__link" href="#">Lake Boundry</a>
        <a class="mdl-navigation__link" href="#">Lake Zones</a>
        <a class="mdl-navigation__link" href="#">Water Balance</a>
        <a class="mdl-navigation__link" href="#">Water Quality</a>
        <a class="mdl-navigation__link" href="#">Evaporation Data</a>
    </nav>
</div>