        <footer class="mdl-mega-footer">
          <div class="mdl-mega-footer--middle-section">   
          </div>
          <div class="mdl-mega-footer--bottom-section">
            <ul class="mdl-mega-footer--link-list">
              <li><a href="http://www.yuktix.com">Yuktix Website</a></li>
              <li><a href="http://blog.yuktix.com">Blog</a></li>
            </ul>
          </div>
        </footer>