<footer class="mdl-mega-footer top-bottom head-foot">
 <div class="mdl-mega-footer--middle-section">
 </div>
 <div class="mdl-mega-footer--bottom-section">
  <div class="mdl-logo">
    More Information
  </div>
  <ul class="mdl-mega-footer--link-list">
    <li><a href="#">About Us</a></li>
    <li><a href="#">Contact Us</a></li>
    <li><a href="#">Privacy and Terms</a></li>
  </ul>
</div>
</footer>