
  <header class="mdl-layout__header">
          	<div class="mdl-layout__header-row">
          		<!-- Title -->
              <div class="mdl-layout-spacer"></div>
          		<span class="mdl-layout-title">Bangalore Lake Dashboard</span>
          		<div class="mdl-layout-spacer"></div>
          		<!-- <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
          		mdl-textfield--floating-label mdl-textfield--align-right">
          	<label class="mdl-button mdl-js-button mdl-button--icon src-btn hide"
          		for="waterfall-exp">
          		<i class="material-icons">search</i>
          	</label>
          	<div class="mdl-textfield__expandable-holder">
          		<input class="mdl-textfield__input" type="text" name="sample"
          		id="waterfall-exp">
          	</div>
          </div> -->
        Rajiv<button id="demo-menu-lower-right"
          class="mdl-button mdl-js-button mdl-button--icon">
          <i class="material-icons">account_box</i>
        </button>

        <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
        for="demo-menu-lower-right">
        <li class="mdl-menu__item">Logout</li>
      </ul>
      </div>
  </header>