
  <footer class="mdl-mega-footer">
        
            <div class="mdl-mega-footer__top-section">
                <div class="mdl-mega-footer__left-section">
                    <a class="mdl-mini-footer__social-btn mdl-button mdl-js-button social-btn"
                        href="#" target="_blank" rel="me" >
                        <img src="/assets/images/twitter_logo.png" width="36px;" height="36px;"> 
                    </a>
                    
                     <a class="mdl-mini-footer__social-btn mdl-button mdl-js-button social-btn"
                        href="#" target="_blank" rel="me" >
                        <img src="/assets/images/facebook-icon-2.png" width="36px;" height="36px;"> 
                    </a>

                     <a class="mdl-mini-footer__social-btn mdl-button mdl-js-button social-btn"
                        href="#" target="_blank" rel="me" >
                        <img src="/assets/images/googleplus-logo.png" width="36px;" height="36px;"> 
                    </a>

                   
                </div>
                <div class="mdl-mega-footer__right-section">
                    <a href="#">About the project</a>
                    <a href="#">Contact us</a>
                    
                </div>
            </div>
            
             <div id="toast-message-container" class="mdl-js-snackbar mdl-snackbar">
                <div class="mdl-snackbar__text"></div>
                <button class="mdl-snackbar__action" type="button"></button>
            </div>
            
    </footer>

