 
  <footer class="mdl-mega-footer">
        
            <div class="mdl-mega-footer__top-section">
                <div class="mdl-mega-footer__left-section">
                    <button class="class="mdl-mega-footer--social-btn social-btn social-btn__twitter"></button>
                    <button class="mdl-mega-footer__social-btn"></button>
                    <button class="mdl-mega-footer__social-btn"></button>
                </div>
                <div class="mdl-mega-footer__right-section">
                    <a href="#">About the project</a>
                    <a href="#">Contact us</a>
                    
                </div>
            </div>
            
             <div id="toast-message-container" class="mdl-js-snackbar mdl-snackbar">
                <div class="mdl-snackbar__text"></div>
                <button class="mdl-snackbar__action" type="button"></button>
            </div>
            
    </footer>

